AguaPotable/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static


from account import urls as accountURLs
from finanzas import urls as finanzasURLs
from waterhole import urls as WaterholeURLs

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include(accountURLs, namespace="account")),
    url(r'^finance/', include(finanzasURLs, namespace="finance")),
    url(r'^waterhole/', include(WaterholeURLs, namespace="waterhole")),

 	url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs={'document_root': settings.MEDIA_ROOT}),   
]

account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login,logout,logout_then_login


urlpatterns = [
	url(r'^profile/$', views.ProfileView.as_view(), name = "profile"),
	#url(r'^main/$', views.MainView.as_view(), name = "main"),
	#URLS the module clients
	url(r'^list-client/$', views.ListClient.as_view(), name = "list-client"),
	url(r'^registry-client/$', views.RegistryClient.as_view(), name = "registry-client"),
	url(r'^detail-client/(?P<id_client>\d+)/(?P<username_client>[-\w]+)/$', views.DetailClient.as_view(), name = "detail-client"),
	#Urls login and logout
	url(r'^login/$', login, name = "login"),
	url(r'^logout-then-login/$', logout_then_login, name='logout-then-login'),

	#Pdf Urls
	url(r'^pdf-contract/pdf/(?P<id_client>\w+)/$', views.PdfSection.contract_pdf, name='pdf_contract'),
	url(r'^pdf-ticket/(?P<id_ticket>\d+)/(?P<id_client>\d+)/$', views.PdfSection.ticket_id_pdf, name='pdf_ticket_id'),
	
	#Url tickets
	url(r'^generate-ticket/(?P<id_client>\d+)/$', views.GenerateTicket.as_view(), name='generate_ticket'),

	#Url graphs
	url(r'^reports-graph/$', views.GraphView.as_view(), name='report'),
	
]

finanzas/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [
	url(r'^ingresos/$', views.ListEarning.as_view(), name = "ingresos"),
	url(r'^registro-ingresos/$', views.RegistryEarning.as_view(), name = "registry-earning"),
	url(r'^egresos/$', views.ListOutflow.as_view(), name = "egresos"),
	url(r'^registro-egresos/$', views.RegistryOutFlow.as_view(), name = "registry-outflow"),

]

finanzas/models.py
from django.db import models
from account.models import WaterHoleProfile
from django.utils.timezone import datetime
import uuid
from decimal import Decimal
from django.db.models import Sum
# Create your models here.

class Earning(models.Model):
	number_registry = models.UUIDField(primary_key=False,default = uuid.uuid4, editable=False)
	subject = models.TextField()
	quantity = models.DecimalField(blank=True, null=True, max_digits = 10, decimal_places = 2)
	date = models.DateTimeField(auto_now_add=True, blank=True)
	admin_waterhole_earning = models.ForeignKey(WaterHoleProfile, related_name='earning_admin',on_delete = models.CASCADE)

	def __str__(self):
		return '{} de {}'.format(self.subject,self.admin_waterhole_earning)

class OutflowsModel(models.Model):
	number_registry = models.UUIDField(primary_key = False, default = uuid.uuid1, editable = False)
	subject = models.TextField()
	quantity = models.DecimalField(blank=True, null=True, max_digits = 10 , decimal_places = 2)
	date = models.DateTimeField(auto_now_add = True)
	admin_waterhole_outflow = models.ForeignKey(WaterHoleProfile,related_name='outflow_admin',on_delete = models.CASCADE)

	def __str__(self):
		return '{} de {}'.format(self.subject,self.quantity)

finanzas/forms.py
from django import forms
from .models import Earning,OutflowsModel
from account.models import User
from account.models import WaterHoleProfile
import datetime


class EarningRegistrationForm(forms.ModelForm):
	subject = forms.CharField(label = "Concepto:",widget=forms.TextInput(attrs={'placeholder':"concepto",}))
	quantity = forms.DecimalField(label = "Costo:",widget=forms.TextInput(attrs={'placeholder':"costo",}))
	#admin_waterhole_earning = forms.ChoiceField(choices=[],widget=forms.TextInput(attrs={'readonly':'True',}))
	

	class Meta:
		model = Earning
		fields = ('subject','quantity')

class OutFlowRegistrationForm(forms.ModelForm):
	subject = forms.CharField(label = 'Concepto',widget = forms.TextInput(attrs = {'placeholder':"Concepto",}))
	quantity = forms.CharField(label = 'Cantidad',widget = forms.TextInput(attrs = {'placeholder':"Cantidad",}))

	class Meta:
		model = OutflowsModel
		fields = ('subject','quantity')

finanzas/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import View
from django.utils.decorators  import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .models import Earning,OutflowsModel
from account.models import User,WaterHoleProfile
from .forms import EarningRegistrationForm,OutFlowRegistrationForm
import pdb
from decimal import Decimal
from django.db.models import Sum
# Create your views here.


#Registro Ingresos
class RegistryEarning(View):
	@method_decorator(login_required)
	def get(self,request):
		template_name = 'registry-earning.html'
		form_earning = EarningRegistrationForm()
		context = {
			"earningactive":"active",
			'form_earning':form_earning,
		}
		
		return render(request,template_name,context)
	def post(self,request):
		template_name = 'registry-earning.html'
		form_earning = EarningRegistrationForm(request.POST)
		user = request.user
		admin = user.get_adminwaterhole_profile()
	
		if form_earning.is_valid():
			new_earning = form_earning.save(commit = False)
			new_earning.admin_waterhole_earning = admin
			new_earning.save()
			messages.success(self.request,'Ingreso registrado')
			return redirect('finance:ingresos')
		
		else:
			form_earning = EarningRegistrationForm()
			context={
				'form_earning':form_earning,
			}
			return render(request,template_name,context)

#Visualizar Ingresos
class ListEarning(View):
	@method_decorator(login_required)
	def get(self,request):
		template_name = 'list-earnings.html'
		earnigns = Earning.objects.order_by('-date')
		total = Earning.objects.aggregate(total=Sum('quantity'))['total']
		paginator = Paginator(earnigns, 10) #de objectos
		page = request.GET.get('page')
		try:
			earnings = paginator.page(page)
		except PageNotAnInteger:
			earnings = paginator.page(1)
		except EmptyPage:
			earnings = paginator.page(paginator.num_pages)
		context ={
			"earningactive":"active",
			'total':total,
			'earnings':earnings,
		}
		
		return render(request,template_name,context)

#Visualizar Egresos
class ListOutflow(View):
	@method_decorator(login_required)
	def get(self,request):
		template_name = 'list_outflows.html'
		outflows = OutflowsModel.objects.order_by('-date')
		total = OutflowsModel.objects.aggregate(total=Sum('quantity'))['total']
		paginator = Paginator(outflows, 10) #de objectos
		page = request.GET.get('page')
		try:
			outflows = paginator.page(page)
		except PageNotAnInteger:
			outflows = paginator.page(1)
		except EmptyPage:
			outflows = paginator.page(paginator.num_pages)
		context ={
			"outflow":"active",
			'outflows':outflows,
			'total':total,
		}
		return render(request,template_name,context)

class RegistryOutFlow(View):
	@method_decorator(login_required)
	def get(self,request):
		template_name = 'registry_outflow.html'
		form_outflow = OutFlowRegistrationForm()
		context = {
			"outflow":"active",
			'form_outflow':form_outflow,
		}
		return render(request,template_name,context)
	
	def post(self,request):
		template_name = 'registry_outflow.html'
		form_outflow = OutFlowRegistrationForm(request.POST)
		user = request.user
		admin = user.get_adminwaterhole_profile()
		if form_outflow.is_valid():
			new_outflow= form_outflow.save(commit = False)
			new_outflow.admin_waterhole_outflow = admin
			new_outflow.save()
			messages.success(self.request,'Egreso registrado')
			return redirect('finance:egresos')
		
		else:
			form_outflow = OutFlowRegistrationForm()
			context={
				'form_outflow':form_outflow,
			}
			return render(request,template_name,context)

finanzas/templates/list-earnings.html
{% extends "base.html" %}
{% load static %}
{% load humanizelib %}
{% load bootstrap%}
{% block content %}


<div class="content">
	
	<a href="{% url 'finance:registry-earning' %}">
	    <button class="btn btn-outline-primary btn-round">
	        <i class="fas fa-pen"></i> Nuevo Ingreso
	    </button>
	</a>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title"> Ingresos</h4>
        <p>Total de Ingresos: <strong> $ {{total|floatformat:2|intcomma}}</strong></p>
        <!--{% if messages %}
          <div id="message" class="messages alert alert-success">
            {% for message in messages %}
            <h3>{{message}}</h3>
            {% endfor %}
          </div>
        {% endif %}-->
      </div>
      <div class="card-body">
        
        <div class="table-responsive">
          <table class="table">
            <thead class=" text-primary">
              <th>
              	# registro
              </th>
              <th>
                Concepto
              </th>
              <th>
                Costo
              </th>
              <th>
              	Fecha
              </th>
              <th>
                Admin
              </th>
            </thead>
            <tbody>
            {% for e in earnings  %}
              <tr>
              	<td>
              	  {{e.number_registry}}
              	</td>
                <td>
                  {{e.subject}} 
                </td>
                <td>
                  $ {{e.quantity}} MXN
                </td>
                <td>
                	{{e.date}}
                </td>
                <td>
                	{{e.admin_waterhole_earning}}
                </td>
              </tr>
            {% endfor %}  
            </tbody>
          </table>
        </div>
    
      </div>
      {% include "pagination.html" with page=earnings %}
    </div>
  </div>
</div>
</div>

{%endblock content%}

finanzas/templates/list_outflows.html
{% extends "base.html" %}
{% load static %}
{% load humanizelib %}
{% load bootstrap%}
{% block content %}


<div class="content">
	
	<a href="{% url 'finance:registry-outflow' %}">
	    <button class="btn btn-outline-primary btn-round">
	        <i class="fas fa-pen"></i> Nuevo Egreso
	    </button>
	</a>
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h4 class="card-title"> Egresos</h4>
        <p>Total de Egresos: <strong> $ {{total|floatformat:2|intcomma}}</strong></p>
        <!--{% if messages %}
          <div id="message" class="messages alert alert-success">
            {% for message in messages %}
            <h3>{{message}}</h3>
            {% endfor %}
          </div>
        {% endif %}-->
      </div>
      <div class="card-body">
        
        <div class="table-responsive">
          <table class="table">
            <thead class=" text-primary">
              <th>
              	# registro
              </th>
              <th>
                Concepto
              </th>
              <th>
                Costo
              </th>
              <th>
              	Fecha
              </th>
              <th>
                Admin
              </th>
            </thead>
            <tbody>
            {% for o in outflows  %}
              <tr>
              	<td>
              	  {{o.number_registry}}
              	</td>
                <td>
                  {{o.subject}} 
                </td>
                <td>
                  $ {{o.quantity}} MXN
                </td>
                <td>
                	{{o.date}}
                </td>
                <td>
                	{{o.admin_waterhole_outflow}}
                </td>
              </tr>
            {% endfor %}  
            </tbody>
          </table>
        </div>
    
      </div>
      {% include "pagination_outflows.html" with page=outflows %}
    </div>
  </div>
</div>
</div>

{%endblock content%}

finanzas/templates/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}">
          <i class="fa fa-angle-left"></i>
          <span class="sr-only">Anterior</span>
        </a>
      </li>
      {%endif%}
      <li class="page-item active"><a class="page-link" href="#">{{ page.number }} </a></li>
      <li class="page-item disabled"><a class="page-link" href="#">de </a></li>
      <li class="page-item"><a class="page-link" href="#">{{ page.paginator.num_pages}} </a></li>
      {% if page.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.next_page_number }}">
          <i class="fa fa-angle-right"></i>
          <span class="sr-only">Siguiente</span>
        </a>
      </li>
      {%endif%}
    </ul>
  </nav>

finanzas/templates/pagination_outflows.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}">
          <i class="fa fa-angle-left"></i>
          <span class="sr-only">Anterior</span>
        </a>
      </li>
      {%endif%}
      <li class="page-item active"><a class="page-link" href="#">{{ page.number }} </a></li>
      <li class="page-item disabled"><a class="page-link" href="#">de </a></li>
      <li class="page-item"><a class="page-link" href="#">{{ page.paginator.num_pages}} </a></li>
      {% if page.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.next_page_number }}">
          <i class="fa fa-angle-right"></i>
          <span class="sr-only">Siguiente</span>
        </a>
      </li>
      {%endif%}
    </ul>
  </nav>

finanzas/templates/registry-earning.html
{% extends "base.html" %}
{% load bootstrap%}
{% load static %}
{% block content %}

<div class="content">
	<div class="col-md-8">
		<div class="card card-user">
		  <div class="card-header">
		    <h5 class="card-title">Registrar Ingreso</h5>
		  </div>
		  <div class="card-body">
		    <form  action="." method="post"  enctype='multipart/form-data'>
		      	{% csrf_token %}
		        {{ form_earning|bootstrap }}
			    <div class="text-right">
			        <input type="submit" name="guardar" value="Registrar" class="btn btn-success">
			    </div>
		    </form>
		  </div>
		</div>
	</div>
</div>
{%endblock content%}

finanzas/templates/registry_outflow.html
{% extends "base.html" %}
{% load bootstrap%}
{% load static %}
{% block content %}

<div class="content">
	<div class="col-md-8">
		<div class="card card-user">
		  <div class="card-header">
		    <h5 class="card-title">Registrar Egreso</h5>
		  </div>
		  <div class="card-body">
		    <form  action="." method="post"  enctype='multipart/form-data'>
		      	{% csrf_token %}
		        {{ form_outflow|bootstrap }}
			    <div class="text-right">
			        <input type="submit" name="guardar" value="Registrar" class="btn btn-success">
			    </div>
		    </form>
		  </div>
		</div>
	</div>
</div>
{%endblock content%}