AguaPotable/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static


from account import urls as accountURLs
from finanzas import urls as finanzasURLs
from waterhole import urls as WaterholeURLs

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include(accountURLs, namespace="account")),
    url(r'^finance/', include(finanzasURLs, namespace="finance")),
    url(r'^waterhole/', include(WaterholeURLs, namespace="waterhole")),

 	url(
        regex=r'^media/(?P<path>.*)$',
        view=serve,
        kwargs={'document_root': settings.MEDIA_ROOT}),   
]

account/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login,logout,logout_then_login


urlpatterns = [
	url(r'^profile/$', views.ProfileView.as_view(), name = "profile"),
	#url(r'^main/$', views.MainView.as_view(), name = "main"),
	#URLS the module clients
	url(r'^list-client/$', views.ListClient.as_view(), name = "list-client"),
	url(r'^registry-client/$', views.RegistryClient.as_view(), name = "registry-client"),
	url(r'^detail-client/(?P<id_client>\d+)/(?P<username_client>[-\w]+)/$', views.DetailClient.as_view(), name = "detail-client"),
	#Urls login and logout
	url(r'^login/$', login, name = "login"),
	url(r'^logout-then-login/$', logout_then_login, name='logout-then-login'),

	#Pdf Urls
	url(r'^pdf-contract/pdf/(?P<id_client>\w+)/$', views.PdfSection.contract_pdf, name='pdf_contract'),
	url(r'^pdf-ticket/(?P<id_ticket>\d+)/(?P<id_client>\d+)/$', views.PdfSection.ticket_id_pdf, name='pdf_ticket_id'),
	
	#Url tickets
	url(r'^generate-ticket/(?P<id_client>\d+)/$', views.GenerateTicket.as_view(), name='generate_ticket'),

	#Url graphs
	url(r'^reports-graph/$', views.GraphView.as_view(), name='report'),
	
]

finanzas/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [
	url(r'^ingresos/$', views.ListEarning.as_view(), name = "ingresos"),
	url(r'^registro-ingresos/$', views.RegistryEarning.as_view(), name = "registry-earning"),
	url(r'^egresos/$', views.ListOutflow.as_view(), name = "egresos"),
	url(r'^registro-egresos/$', views.RegistryOutFlow.as_view(), name = "registry-outflow"),

]

waterhole/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^comite/$', views.ComitteView.as_view(), name='comitte'),	
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../assets/img/favicon.png">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Dosis" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
  <!-- CSS Files -->
  <link href="{% static 'css/bootstrap.min.css' %} " rel="stylesheet" />
  <link href="{% static 'css/paper-dashboard.css' %} " rel="stylesheet" />
  

</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="white" data-active-color="danger">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
      <div class="logo">
        <a href="#" class="simple-text logo-mini">
          <div class="logo-image-small">
            <img src="{% static 'img/logo-pc.png' %} ">
          </div>
        </a>
        <a href="#" class="simple-text logo-normal">
          Pozo Cozotlan A.C.
          <!-- <div class="logo-image-big">
            <img src="../assets/img/logo-big.png">
          </div> -->
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          {% if request.user.is_authenticated %}
          <li class="{{profileclass}}">
            <a href="{% url 'account:profile' %}">
              <i class="fas fa-address-card"></i>
              <p>Perfíl</p>
            </a>
          </li>
          <li class="{{mainclient}}">
            <a href="{% url 'account:list-client' %}">
              <i class="fas fa-users"></i>
              <p>Clientes</p>
            </a>
          </li>
          <li class="{{report}}">
            <a href="{% url 'account:report' %}">
              <i class="fas fa-clipboard-check"></i>
              <p>Reportes</p>
            </a>
          </li>
          <li class="{{earningactive}}">
            <a href="{% url 'finance:ingresos' %}">
              <i class="fas fa-hand-holding-usd"></i>
              <p>Ingresos</p>
            </a>
          </li>
          <li class="{{outflow}}">
            <a href="{% url 'finance:egresos'%}">
              <i class="fas fa-file-invoice-dollar"></i>
              <p>Egresos</p>
            </a>
          </li>
          <li class="{{comittte}}">
            <a href="{% url 'waterhole:comitte' %}">
              <i class="fas fa-users-cog"></i>
              <p>Comité</p>
            </a>
          </li>
          <li>
            <a href="{% url 'account:logout-then-login' %}">
              <i class="fas fa-sign-out-alt"></i>
              <p>Cerrar Sesión</p>
            </a>
          </li>
          {% else %}
          <li>
            <a href="{% url 'account:login' %}">
              <i class="fas fa-file-invoice-dollar"></i>
              <p>Iniciar Sesión</p>
            </a>
          </li>        
          {% endif %} 
        </ul> 
      </div>
    </div>

    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute fixed-top navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="#pablo">Sistema Comunitario de Agua Potable</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <!-- <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <form>
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="nc-icon nc-zoom-split"></i>
                  </div>
                </div>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link btn-magnify" href="#pablo">
                  <i class="nc-icon nc-layout-11"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Stats</span>
                  </p>
                </a>
              </li>
              <li class="nav-item btn-rotate dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="nc-icon nc-bell-55"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Some Actions</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link btn-rotate" href="#pablo">
                  <i class="nc-icon nc-settings-gear-65"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Account</span>
                  </p>
                </a>
              </li>
            </ul>
          </div> -->
        </div>
      </nav>
  
      <!-- End Navbar -->
      <!-- <div class="panel-header panel-header-sm">-->
    {% block content %}

      
    {% endblock content %}

    <footer class="footer footer-black  footer-white ">
      <div class="container-fluid">
          <div class="row">
            <nav class="footer-nav">
              <ul>
                <li>
                  <a href="" target="_blank"></a>
                </li>
                <li>
                  <a href="" target="_blank"></a>
                </li>
                <li>
                  <a href="" target="_blank"></a>
                </li>
              </ul>
            </nav>
            <div class="credits ml-auto">
              <span class="copyright">
                ©
                <script>
                  document.write(new Date().getFullYear())
                </script>, made with <i class="fa fa-heart heart"></i> by FullStack Community
              </span>
            </div>
          </div>
        </div>
    </footer>
  </div>
  <!--   Core JS Files   -->
  <script rel="javascript" type="text/javascript" href="js/jquery-1.11.3.min.js"></script>
  <script src="{% static 'js/core/jquery.min.js' %} "></script>
  <script src="{% static 'js/core/popper.min.js' %} "></script>
  <script src="{% static 'js/core/bootstrap.min.js' %} "></script>
  <script src="{% static 'js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!--  Google Maps Plugin    -->
  <!--<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>-->
  <!-- Chart JS -->
  <!--<script src=" {% static 'js/plugins/chartjs.min.js' %}"></script>-->
  <!--  Notifications Plugin    -->
  <script src=" {% static 'js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src=" {% static 'js/paper-dashboard.min.js' %}" type="text/javascript"></script>
 
  <script type="text/javascript">
    setTimeout(function() {
      $('#message').hide()
    }, 1000);
  </script>
  
</body>

</html>